server:
  port: 8089
  
spring:
  application:
    name: order-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
#    druid:
#      initial-size: 5
#      min-idle: 5
#      max-active: 20
#      max-wait: 1000
#      test-on-borrow: true
  jackson:
    default-property-inclusion: non_null #JSON过滤对象为空属性
  rabbitmq:
    host: 192.168.1.10
    username: root
    password: root
    virtual-host: /leyou
    template:
      retry:
        enabled: true
        initial-interval: 10000ms
        max-interval: 300000ms
        multiplier: 2
      exchange: ly.item.exchange
    publisher-confirms: true
  redis:
    host: 192.168.1.128

eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 5
  instance:
    lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
    lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}.${server.port}

mybatis:
  type-aliases-package: com.leyou.order.pojo
#  mapper-locations: mapper/OrderMapper.xml
#  configuration:
#    map-underscore-to-camel-case: true
#mapper:
#  not-empty: false
#  identity: mysql
ly:
  worker:
    workerId: 1
    datacenterId: 1
  jwt:
    pubKeyPath: D:\Java\rsa\rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
  pay:
    appId: wx8397f8696b538317
    mchId: 1473426802
    key: T6m9iK73b0kn9g5v426MKfHQH7X8rKwb
    connectTimeoutMs: 5000
    readTimeoutMs: 10000
    notifyUrl: http://oywworg.oicp.net/notify
