server:
  port: 8085
spring:
  application:
    name: user-service
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/leyou
    username: root
    password: 1234
    driver-class-name: com.mysql.jdbc.Driver
  rabbitmq:
    host: 192.168.1.10
    username: root
    password: root
    virtual-host: /leyou
  redis:
    host: 192.168.1.128

eureka:
  client:
    service-url:
      defaultZone:  http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
      lease-renewal-interval-in-seconds: 5 # 每隔5秒发送一次心跳
      lease-expiration-duration-in-seconds: 10 # 10秒不发送就过期
      prefer-ip-address: true
      ip-address: 127.0.0.1
      #instance-id: ${eureka.instance.ip-address}:${server.port}在注册中心Status显示的是ip地址加端口
      instance-id: ${eureka.instance.ip-address}_${spring.application.name}:${server.port} #在注册中心Status显示的是服务名加端口
mybatis:
  type-aliases-package: com.leyou.user.pojo