server:
  port: 8088
spring:
  application:
    name: cart-service
  redis:
    host: 192.168.1.128
  rabbitmq:
    host: 192.168.1.10
    username: root
    password: root
    virtual-host: /leyou
eureka:
  client:
    service-url:
      defaultZone: http://127.0.0.1:10086/eureka
    registry-fetch-interval-seconds: 10
  instance:
    prefer-ip-address: true
    ip-address: 127.0.0.1
    instance-id: ${spring.application.name}:${server.port}
    lease-renewal-interval-in-seconds: 5
    lease-expiration-duration-in-seconds: 15
ly:
  jwt:
    pubKeyPath: D:/java/rsa/rsa.pub # 公钥地址
    cookieName: LY_TOKEN # cookie的名称
